journal/urls.py
"""Defines URL patterns for journal."""

from django.urls import path

from . import views

app_name = 'journal'
urlpatterns = [
    # Home Page
    path('', views.index, name='index'),
    # Page that shows all public topics.
    path('public_topics/', views.public_topics, name='public_topics'),
    # Detail page for a single public topic.
    path('public_topics/<int:topic_id>/', views.public_topic, name='public_topic'),
    # Page for corona stats.
    path('public_topics/corona_stats_ch/', views.corona_stats_ch, name='corona_stats_ch'),
    # URL for /dashboard/covid.
    path('covid/', views.corona_stats_ch, name='dashboard_covid'),
    # URL for /dashboard/us-air-passengers.
    path('us-air-passengers/', views.us_air_passenger_stats, name='dashboard_us-air-passengers'),
    # Page for visitor details.
    path('visitors/', views.visitors, name='visitors'),
    # Page that shows all topics.
    path('topics/', views.topics, name='topics'),
    # Detail page for a single topic.
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Page for adding a new topic
    path('new_topic/', views.new_topic, name='new_topic'),
    # Page for adding a new entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Page for editing an entry.
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

knowledge_journal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('journal.urls')),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

journal/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    """A topic the user is learning about."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text

class Entry(models.Model):
    """Something specific learned about a topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model."""
        if len(self.text) < 50:
            return self.text
        else:
            return f"{self.text[:50]}..."

journal/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

journal/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

import os.path
from os import path

from .cantonal_rankings import rankings
from .us_air_passenger_volume import passenger_volume
from datetime import datetime, timedelta

from .visitor_tracker import visitor_tracker
from .visitor_tracker import download_blob

def index(request):
    """The home page for Learning Log."""
    #visitor_tracker(request)
    return render(request, 'journal/index.html')

def public_topics(request):
    """Show all public topics."""
    topics = Topic.objects.filter(owner=3).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'journal/public_topics.html', context)

def public_topic(request, topic_id):
    """Show a single public topic and all its entries."""
    topic = Topic.objects.get(id=topic_id, owner=3)
    # Make sure the topic belongs to the current user.

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'journal/public_topic.html', context)

def corona_stats_ch(request):
    #visitor_tracker(request)
    yesterday_raw = datetime.now() - timedelta(days=1)
    yesterday = yesterday_raw.strftime("%Y-%m-%d")
    corona_stats_ch_loc = f'/tmp/corona_stats_{yesterday}.html'
    if path.exists(corona_stats_ch_loc):
        return render(request, corona_stats_ch_loc)
    else:
        url = rankings()[0]
        status_code = rankings()[1]
        if status_code != "200":
            context = {"url": url, "status_code": status_code}
            return render(request, 'journal/API_problem.html', context)
        if path.exists(corona_stats_ch_loc):
            return render(request, corona_stats_ch_loc)
        else:
            return render(request, 'journal/corona_stats_not_exist.html')

def us_air_passenger_stats(request):
    us_air_passenger_stats_loc = "/tmp/us-air-passengers.html"
    if path.exists(us_air_passenger_stats_loc):
        return render(request, us_air_passenger_stats_loc)
    else:
        status_code = passenger_volume()[1]
        if status_code != "200":
            context = {"url": "https://www.tsa.gov/coronavirus/passenger-throughput", "status_code": status_code}
            return render(request, 'journal/API_problem_TSA.html', context)
        else:
            return render(request, us_air_passenger_stats_loc)

@login_required
def topics(request):
    """Show all topics."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'journal/topics.html', context)

@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)
    # Make sure the topic belongs to the current user.
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'journal/topic.html', context)

@login_required
def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('journal:topics')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'journal/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
        
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('journal:topic', topic_id=topic_id)

    # Display a blank or invalid form.
    context = { 'topic': topic, 'form': form}
    return render(request, 'journal/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit and existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initail request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted, process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('journal:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'journal/edit_entry.html', context)

@login_required
def visitors(request):
    bucket_name = 'knowledge-journal.appspot.com'
    source_blob_name = 'visitors.html'
    destination_file_name = '/tmp/visitorss.html'
    download_blob(bucket_name, source_blob_name, destination_file_name)
    return render(request, destination_file_name)

journal/templates/journal/base.html
    <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-174690578-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-174690578-1');
</script>

<p>
    <a href="{% url 'journal:index' %}">Knowledge Journal</a> -
    <a href="{% url 'journal:topics' %}">Topics</a> -
    {% if user.is_authenticated %}
        Hello, {{ user.username }}.
        <a href="{% url 'users:logout' %}">Log out</a>
    {% else %}
        <a href="{% url 'users:register' %}">Register</a> -
        <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}
</p>

{% block content %}{% endblock content %}

journal/templates/journal/corona_stats_not_exist.html
{% extends "journal/base.html" %}

{% block content %}

There is no data available for yesterday. 
That probably means "Corona" is not a thread anymore. Good for us!

{% endblock content %}

journal/templates/journal/edit_entry.html
{% extends "journal/base.html" %}
{% block content %}

    <p><a href="{% url 'journal:topic' topic.id %}">{{ topic }}</a></p>

    <p>Edit entry:</p>

    <form action="{% url 'journal:edit_entry' entry.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save changes</button>
    </form>

{% endblock content %}

journal/templates/journal/index.html
{% extends "journal/base.html" %}

{% block content %}
    <p>Knowledge Journal helps you keep track of your learning notes.</p>
    <p>Login to access your own journal</p>

    <p>Here are some public journal topics:
    <ul>
        <a href="{% url 'journal:public_topics'%}"> Public Topics </a>
    </ul>

{% endblock content %}

journal/templates/journal/new_entry.html
{% extends "journal/base.html" %}

{% block content %}

    <p><a href="{% url 'journal:topic' topic.id %}">{{ topic }}</a></p>

    <p>Add a new entry:</p>
    <form action="{% url 'journal:new_entry' topic.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name='submit'>Add entry</button>
    </form>

{% endblock content %}

journal/templates/journal/new_topic.html
{% extends "journal/base.html" %}

{% block content %}

    <p>Add a new topic:</p>

    <form action="{% url 'journal:new_topic' %}" method='post' >
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add topic</button>
    </form>

{% endblock content %}

journal/templates/journal/public_topic.html
{% extends "journal/base.html" %}

{% block content %}

    <p>Topic: {{ topic }}</p>
    <p>Entries:</p>
    <ul>
    {% for entry in entries %}
        <li>
            <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
            <p>{{ entry.text|linebreaks }}</p>
        </li>
    {% empty %}
        <li>There are no entries for this topic yet.</li>
    {% endfor %}
    </ul>

{% endblock content%}

journal/templates/journal/public_topics.html
{% extends "journal/base.html" %}

{% block content %}

    <p>Topics</p>

    <ul>
        {% for topic in topics %}
            <li>
                <a href="{% url 'journal:public_topic' topic.id %}"> {{ topic }}</a>
            </li>
        {% empty %}
            <li>No topics have been added yet.</li>
        {% endfor %}
    </ul>

{% endblock content %}

journal/templates/journal/topic.html
{% extends "journal/base.html" %}

{% block content %}

    <p>Topic: {{ topic }}</p>
    <p>Entries:</p>
    <p>
        <a href="{% url 'journal:new_entry' topic.id %}">Add new entry</a>
    </p>
    <ul>
    {% for entry in entries %}
        <li>
            <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
            <p>{{ entry.text|linebreaks }}</p>
            <p>
                <a href="{% url 'journal:edit_entry' entry.id %}">Edit entry</a>
            </p>
        </li>
    {% empty %}
        <li>There are no entries for this topic yet.</li>
    {% endfor %}
    </ul>

{% endblock content%}

journal/templates/journal/topics.html
{% extends "journal/base.html" %}

{% block content %}

    <p>Topics</p>

    <ul>
        {% for topic in topics %}
            <li>
                <a href="{% url 'journal:topic' topic.id %}"> {{ topic }}</a>
            </li>
        {% empty %}
            <li>No topics have been added yet.</li>
        {% endfor %}
    </ul>

    <a href="{% url 'journal:new_topic' %}">Add a new topic</a>

{% endblock content %}